export const MonthlyData = [
  {
    id: 1,
    type: 'Free Trial',
    price: 0,
    duration: '7 days',
    desc: 'Explore the gifting experience risk-free! Dive into our platform and see how it works before committing to a monthly plan.',
    features: [
      'Full access to explore the Gift Shop with 15% off.',
      'Experience how gifting works without actual gift delivery.',
      'Upgrade to any plan anytime after the trial.',
    ],
  },
  {
    id: 301,
    type: 'Budget Friendly',
    price: 15,
    duration: 'month',
    desc: 'Perfect for the occasional gifter. Receive 1-2 surprise gifts per event for up to two holidays or events per month.',
    features: [
      '1-2 surprise gifts per event (based on balance).',
      'Standard gift wrapping style.',
      'Access to add-on features for enhanced gifting experiences.',
      'Rollover unused funds for future gifts.',
      'Receive $5 Credit to budget balance when you subscribe.',
    ],
  },
  {
    id: 302,
    type: 'Premium Plan',
    price: 30,
    duration: 'month',
    recoment: true,
    desc: 'Perfect for celebrating more! Enjoy multiple gifts or one gift per event for up to 4 holidays/events per month.',
    features: [
      'Covers up to 4 holidays/events per month.',
      'Multiple gifts per event (if funds allow).',
      'Customizable gift preferences (themes, colors).',
      'Premium gift wrapping with personalized notes.',
      'Rollover unused funds to future gifts or increase gift value.',
      'Receive a free surprise gift when you subscribe.',
      'Receive $10 Credit to budget balance when you subscribe.',
    ],
  },
  {
    id: 303,
    type: 'Spoiling Myself',
    price: 50,
    duration: 'month',
    desc: 'The ultimate gifting experience. Indulge in unlimited gifts for all your special occasions throughout the month.',
    features: [
      'Unlimited gift options for all events (subject to balance).',
      'Surprise “just because” gifts throughout the month.',
      'Luxury gift wrapping with personalized notes and premium packaging.',
      'Access to Discounted Gift Shop Items.',
      'Priority support for customizing preferences and upgrades.',
      'Rollover unused funds to future gifts or increase gift value.',
      'Receive a free surprise gift when you subscribe.',
      'Receive $10 Credit to budget balance when you subscribe.',
    ],
  },
];

export const YearlyData = [
  {
    id: 1,
    type: 'Free Trial',
    price: 0,
    duration: '7 days',
    desc: 'Explore the gifting experience risk-free! Dive into our platform and see how it works before committing to a yearly plan.',
    features: [
      'Full access to explore the Gift Shop with 15% off.',
      'Experience how gifting works without actual gift delivery.',
      'Upgrade to any plan anytime after the trial.',
    ],
  },
  {
    id: 121,
    type: 'Budget Friendly',
    price: 171,
    duration: 'year',
    desc: 'Perfect for the occasional gifter. Receive 1-2 surprise gifts per event for up to two holidays or events per year.',
    features: [
      '1-2 surprise gifts per event (based on balance).',
      'Standard gift wrapping style.',
      'Access to add-on features for enhanced gifting experiences.',
      'Rollover unused funds for future gifts.',
      'Receive $5 Credit to budget balance when you subscribe.',
    ],
  },
  {
    id: 122,
    type: 'Premium Plan',
    price: 342,
    duration: 'year',
    recoment: true,
    desc: 'Perfect for celebrating more! Enjoy multiple gifts or one gift per event for up to 4 holidays/events per year.',
    features: [
      'Covers up to 4 holidays/events per year.',
      'Multiple gifts per event (if funds allow).',
      'Customizable gift preferences (themes, colors).',
      'Premium gift wrapping with personalized notes.',
      'Rollover unused funds to future gifts or increase gift value.',
      'Receive a free surprise gift when you subscribe.',
      'Receive $10 Credit to budget balance when you subscribe.',
    ],
  },
  {
    id: 123,
    type: 'Spoiling Myself',
    price: 570,
    duration: 'year',
    desc: 'The ultimate gifting experience. Indulge in unlimited gifts for all your special occasions throughout the year.',
    features: [
      'Unlimited gift options for all events (subject to balance).',
      'Surprise “just because” gifts throughout the year.',
      'Luxury gift wrapping with personalized notes and premium packaging.',
      'Access to Discounted Gift Shop Items.',
      'Priority support for customizing preferences and upgrades.',
      'Rollover unused funds to future gifts or increase gift value.',
      'Receive a free surprise gift when you subscribe.',
      'Receive $10 Credit to budget balance when you subscribe.',
    ],
  },
];
